---
# Source: todo-frontend/templates/todo-frontend-service.yml
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 3000
