---
# Source: todo-backend/templates/postgres-pv-claim.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  storageClassName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
