---
# Source: todo-backend/templates/postgres-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: dG9kbzEyMw==
  dbName: cG9zdGdyZXM=
